name: fabric_generator
description: Generator for Fabric
version: 0.1.0
repository: https://github.com/stijnvanbael/fabric/tree/master/generator

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.2.0
  build: ^2.3.1
  source_gen: ^1.2.7
  merging_builder_svb:
    path: ../../merging_builder
  fabric_manager:
    path: ../manager
  fabric_metadata:
    path: ../metadata

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
