name: fabric_generator
description: Generator for Fabric
version: 0.0.6
repository: https://github.com/stijnvanbael/fabric/tree/master/generator

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  analyzer: ^5.2.0
  build: ^2.3.1
  source_gen: ^1.2.6
  merging_builder_svb: ^0.2.4
  fabric_manager: ^0.0.6
  fabric_metadata: ^0.0.4

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
