builders:
  fabric_test_generator:
    import: "package:fabric_generator/fabric_generator.dart"
    builder_factories: [ "fabricBuilder" ]
    build_extensions: { "*/$package$": [ "fabric.g.dart" ] }
    auto_apply: root_package
    build_to: source
    defaults:
      options: { "folder": "test" }
