name: fabric_metadata
description: Metadata for Fabric
version: 0.0.2
repository: https://github.com/stijnvanbael/fabric/tree/master/metadata

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.10
  fabric_generator: ^0.0.2
  fabric_manager: ^0.0.2
