name: fabric_metadata
description: Metadata for Fabric
version: 0.0.3
repository: https://github.com/stijnvanbael/fabric/tree/master/metadata

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
  build_runner: ^2.3.2
  fabric_generator: ^0.0.3
  fabric_manager: ^0.0.3
