name: fabric_metadata
description: Metadata for Fabric
version: 0.0.1

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.10
  fabric_generator:
    path: ../generator
  fabric_manager:
    path: ../manager
