name: fabric_manager
description: Manager for Fabric
version: 0.1.0
repository: https://github.com/stijnvanbael/fabric/tree/master/manager

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fabric_metadata:
    path: ../metadata

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
