name: fabric_manager
description: Manager for Fabric
version: 0.0.1

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  fabric_metadata:
    path: ../metadata

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
