builders:
  controller_generator:
    target: ":controller_generator"
    import: "package:controller_generator/controller_generator.dart"
    builder_factories: [ "controllerBuilder" ]
    build_extensions: { ".dart": [ ".controller_generator.g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]

  box_generator:
    target: ":box_generator"
    import: "package:box_generator/box_generator.dart"
    builder_factories: ["registryBuilder"]
    build_extensions: {".dart": [".box_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  json_serializable:
    import: "package:json_serializable/builder.dart"
    builder_factories: ["jsonSerializable"]
    build_extensions: {".dart": ["json_serializable.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  weaver_lib_generator:
    import: "package:fabric_weaver_generator/fabric_weaver_generator.dart"
    builder_factories: [ "dispatcherLibBuilder", "boxRegistryLibBuilder", "applicationLibBuilder" ]
    build_extensions:
      "lib/$lib$": [ "lib/weaver.g.dart" ]
    auto_apply: root_package
    build_to: source
  weaver_test_generator:
    import: "package:fabric_weaver_generator/fabric_weaver_generator.dart"
    builder_factories: [ "dispatcherTestBuilder", "boxRegistryTestBuilder", "applicationTestBuilder" ]
    build_extensions:
      "test/$package$": [ "test/weaver.g.dart" ]
    auto_apply: root_package
    build_to: source
  weaver_example_generator:
    import: "package:fabric_weaver_generator/fabric_weaver_generator.dart"
    builder_factories: [ "dispatcherExampleBuilder", "boxRegistryExampleBuilder", "applicationExampleBuilder" ]
    build_extensions:
      "test/$package$": [ "example/weaver.g.dart" ]
    auto_apply: root_package
    build_to: source
