name: fabric_weaver_generator
description: Generator for Fabric Weaver
version: 0.0.2

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  build: ^2.3.0
  source_gen: ^1.2.2
  merging_builder: #^0.2.3
    path: ../../merging_builder
  controller: ^0.1.4
  box: ^0.3.3+2
  fabric_generator: #^0.0.2
    path: ../generator
  controller_generator: #^0.1.4
    path: ../../controller_generator
  box_generator: #^0.3.3+2
    path: ../../box_generator
  json_serializable: ^6.2.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
