name: fabric_weaver_generator
description: Generator for Fabric Weaver
version: 0.0.8

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  analyzer: ^5.11.1
  build: ^2.3.1
  source_gen: ^1.2.7
  merging_builder_svb: ^0.2.4
  controller: ^0.1.12
  box: ^0.3.7
  fabric_generator: ^0.0.6
  controller_generator: ^0.1.9
  box_generator: ^0.3.6
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
