name: fabric_weaver_generator
description: Generator for Fabric Weaver
version: 0.0.8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.2.0
  build: ^2.3.1
  source_gen: ^1.2.7
  merging_builder_svb:
    path: ../../merging_builder
  controller:
    path: ../../controller
  box:
    path: ../../box
  fabric_generator:
    path: ../generator
  controller_generator:
    path: ../../controller_generator
  box_generator:
    path: ../../box_generator
  json_serializable: ^6.6.1
  retrofit_generator: 7.0.8

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
