builders:
  weaver_example_generator:
    import: "package:fabric_weaver_generator/fabric_weaver_generator.dart"
    builder_factories: [ "dispatcherBuilder", "boxRegistryBuilder", "applicationBuilder" ]
    build_extensions: { "*/$package$": [ "weaver.g.dart" ] }
    auto_apply: root_package
    build_to: source
    defaults:
      options: { "folder": "example" }
  fabric_example_generator:
    import: "package:fabric_generator/fabric_generator.dart"
    builder_factories: [ "fabricBuilder" ]
    build_extensions: { "*/$package$": [ "fabric.g.dart" ] }
    auto_apply: root_package
    build_to: source
    defaults:
      options: { "folder": "example" }

