name: fabric_weaver
description: Application bootstrapper
version: 0.0.2

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  fabric_manager: ^0.0.2
  fabric_metadata: ^0.0.2
  controller: ^0.1.4
  box: ^0.3.3+2
  shelf: ^1.3.0
  logging: ^1.0.2
  json_annotation: ^4.5.0
  yaml: ^3.1.1
  args: ^2.3.1

dev_dependencies:
  build_runner: ^2.1.10
  fabric_weaver_generator: #^0.0.2
    path: ../weaver_generator
  lints: ^1.0.0
  test: ^1.16.0
