name: fabric_weaver
description: Application bootstrapper
version: 0.0.1

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  fabric_manager: #^0.0.1
    path: ../manager
  fabric_metadata: #^0.0.1
    path: ../metadata
  controller:
    path: ../../controller
  box:
    path: ../../box
  shelf: ^1.3.0
  logging: ^1.0.2
  json_annotation: ^4.5.0

dev_dependencies:
  build_runner: ^2.1.10
  fabric_generator: #^0.0.1
    path: ../generator
  fabric_weaver_generator: #^0.0.1
    path: ../weaver_generator
  controller_generator:
    path: ../../controller_generator
  box_generator:
    path: ../../box_generator
  json_serializable: ^6.2.0
  lints: ^1.0.0
  test: ^1.16.0
