name: fabric_weaver
description: Application bootstrapper
version: 0.0.5

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  fabric_manager: ^0.0.4
  fabric_metadata: ^0.0.4
  controller: ^0.1.4
  box: ^0.3.4
  shelf: ^1.3.0
  logging: ^1.0.2
  json_annotation: ^4.7.0
  yaml: ^3.1.1
  args: ^2.3.1
  retrofit: ^3.3.1
  dio: ^4.0.6
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.1.10
  fabric_weaver_generator:
    path: ../weaver_generator
  lints: ^2.0.1
  test: ^1.16.0
