name: fabric_weaver
description: Application bootstrapper
version: 0.0.16

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  fabric_manager: ^0.0.6
  fabric_metadata: ^0.0.4
  controller: ^0.1.11
  box: ^0.3.6
  shelf: ^1.3.0
  functions_framework: ^0.4.1
  logging: ^1.0.2
  json_annotation: ^4.7.0
  yaml: ^3.1.1
  args: ^2.4.0
  retrofit: ^3.3.1
  dio: ^4.0.6
  intl: ^0.18.0
  hotreloader: ^3.0.5
  shutdown: ^0.4.3
  encrypt: ^5.0.1

dev_dependencies:
  build_runner: ^2.3.3
  fabric_weaver_generator:
    path: ../weaver_generator
  lints: ^2.0.1
  test: ^1.23.1
