name: fabric_weaver
description: Application bootstrapper
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fabric_manager:
    path: ../manager
  fabric_metadata:
    path: ../metadata
  controller:
    path: ../../controller
  box:
    path: ../../box
  shelf: ^1.4.0
  functions_framework: ^0.4.1
  logging: ^1.1.1
  json_annotation: ^4.8.0
  yaml: ^3.1.1
  args: ^2.4.0
  retrofit: ^4.0.1
  dio: ^5.0.0
  intl: ^0.18.1
  hotreloader: ^4.0.0
  shutdown: ^0.4.3
  cipher_string: ^0.0.1

dev_dependencies:
  build_runner: ^2.3.3
  fabric_weaver_generator:
    path: ../weaver_generator
  lints: ^2.0.1
  test: ^1.24.2