name: fabric_prefab_example

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fabric_prefab:
    path: ..
  build_web_compilers: ^4.0.5
  build_runner: ^2.1.10

dev_dependencies:
  fabric_prefab_generator:
    path: ../../prefab_generator