POST http://localhost:8080/todos
content-type: application/json

{
  "description": "Book ski trip"
}

###

GET http://localhost:8080/todos/book-ski-trip

###

POST http://localhost:8080/todos/book-ski-trip/done

###

PUT http://localhost:8080/todos/book-ski-trip/description
content-type: application/json

{
  "description": "Book two ski trips"
}
